# Generated by Django 5.2.4 on 2025-08-14 10:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=120, verbose_name='Subtitle')),
                ('url_title', models.CharField(db_index=True, max_length=120, verbose_name='URL Subtitle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted?')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('price', models.IntegerField(verbose_name='Price')),
                ('rating', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(null=True, verbose_name='Active / Deactive')),
                ('short_description', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, db_index=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted?')),
                ('category', models.ManyToManyField(related_name='product_categories', to='eshop.productcategory', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=120, verbose_name='Tag')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.product', verbose_name='ProductTags')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
